[template]
src = "ipsec.hidden_pubip_host.conf.tmpl"
prefix = "/ipsec"
dest = "/etc/ipsec.config.d/ipsec.hidden_pubip_host.conf"
keys = [
    "/localip",
    "/localid",
    "/remoteip",
    "/remoteid",
    "/localnet",
    "/remotenet",
    "/keyexchange",
    "/espcipher",
    "/ikecipher",
    "/forceudp"
]
